env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true
rules: {}
