env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  # https://eslint.org/docs/rules/
  # eqeqeq: warn
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/no-extra-parens': warn
  '@typescript-eslint/no-useless-constructor': warn
  array-bracket-spacing:
    - warn
    - never
  arrow-body-style:
    - warn
    - as-needed
  arrow-parens:
    - warn
    - as-needed
  arrow-spacing: warn
  brace-style:
    - warn
    - stroustrup
    - allowSingleLine: true
  curly: warn
  dot-notation: warn
  eol-last: warn
  func-call-spacing: warn
  indent:
    - warn
    - 4
    - SwitchCase: 1
  key-spacing: warn
  keyword-spacing: warn
  max-len:
    - off
    - 120
  no-array-constructor: warn
  no-duplicate-imports: warn
  no-lonely-if: warn
  no-multi-spaces: warn
  no-multiple-empty-lines:
    - warn
    - max: 1
  no-new-wrappers: warn
  no-trailing-spaces: warn
  no-unneeded-ternary: warn
  no-useless-return: warn
  no-var: warn
  no-whitespace-before-property: warn
  object-shorthand: warn
  object-curly-spacing:
    - warn
    - always
  padded-blocks:
    - warn
    - never
  prefer-arrow-callback: warn
  prefer-const: warn
  prefer-destructuring:
    - warn
    - object: true
      array: true
  quotes:
    - warn
    - single
    - avoidEscape: true
  react/jsx-indent: warn
  react/no-typos: warn
  # Disable react/prop-types, because it complains about types that could be inferred when using React.FC<Props>.
  react/prop-types: off
  semi: warn
  template-curly-spacing: warn
  unicode-bom: warn
  yoda: warn
reportUnusedDisableDirectives: true
settings:
  react:
    version: detect
